
#checksum_gui:checksum_gui.c
#	@gcc -Wall -g -o checksum_gui checksum_gui.c `pkg-config --cflags --libs gtk+-2.0` && ./checksum_gui

main:main.c
 	@gcc -Wall -g -o main main.c -lssl -lcrypto -lpthread